# Generated by Django 4.2.2 on 2023-06-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('orders', '0003_alter_order_total_cost')]

    operations = [
        migrations.AddConstraint(
            model_name='orderproduct',
            constraint=models.UniqueConstraint(fields=('order', 'product'), name='unique_product_order'),
        )
    ]
