# Generated by Django 4.2.2 on 2023-06-21 19:21

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('orders', '0004_orderproduct_unique_product_order')]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='phone',
            field=models.CharField(
                max_length=30, null=True, validators=[common.validators.validate_phone], verbose_name='Телефон'
            ),
        ),
    ]
