# Generated by Django 4.2.2 on 2023-06-21 19:26

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('orders', '0005_alter_delivery_address_alter_delivery_phone')]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='address',
            field=models.CharField(default=1, max_length=200, verbose_name='Адрес'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='phone',
            field=models.CharField(
                default=1, max_length=30, validators=[common.validators.validate_phone], verbose_name='Телефон'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='type_delivery',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name='delivery',
                to='orders.deliverytype',
                verbose_name='Доставка',
            ),
        ),
    ]
