# Generated by Django 4.2.2 on 2023-06-22 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('product', '0001_initial'),
        ('orders', '0006_alter_delivery_address_alter_delivery_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders_delivery',
                to='orders.delivery',
                verbose_name='Доставка',
            ),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders_product',
                to='orders.order',
                verbose_name='Заказ',
            ),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='products_in_order',
                to='product.product',
                verbose_name='Товар',
            ),
        ),
    ]
