# Generated by Django 4.2.2 on 2023-06-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('orders', '0009_alter_order_total_cost')]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=40, verbose_name='Общая стоимость'),
        )
    ]
