# Generated by Django 4.2.2 on 2023-06-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('orders', '0010_alter_order_total_cost')]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=40, verbose_name='Стоимость'),
        )
    ]
