# Generated by Django 4.2.2 on 2023-06-24 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('orders', '0012_alter_order_total_cost')]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_products',
                to='orders.order',
                verbose_name='Заказ',
            ),
        )
    ]
