# Generated by Django 4.2.2 on 2023-06-26 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('product', '0007_alter_product_furniture_details'), ('orders', '0013_alter_orderproduct_order')]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='type_delivery',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='delivery',
                to='orders.deliverytype',
                verbose_name='Доставка',
            ),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders_delivery',
                to='orders.delivery',
                verbose_name='Доставка',
            ),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='order_products',
                to='product.product',
                verbose_name='Товар',
            ),
        ),
    ]
