# Generated by Django 4.2.1 on 2023-06-03 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка на категорию')),
            ],
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название материала')),
            ],
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.IntegerField(unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                ('width', models.IntegerField(verbose_name='Ширина, см')),
                ('height', models.IntegerField(verbose_name='Высота, см')),
                ('length', models.IntegerField(verbose_name='Длина, см')),
                ('weight', models.IntegerField(verbose_name='Вес, кг')),
                ('color', models.CharField(verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='', verbose_name='Фотография продукта')),
                ('country', models.CharField(verbose_name='Страна-производитель')),
                ('brand', models.CharField(null=True, verbose_name='Бренд')),
                ('warranty', models.IntegerField(null=True, verbose_name='Гарантия , лет')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.CharField(verbose_name='Описание')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='product.categories', verbose_name='Категория'
                    ),
                ),
                (
                    'material',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='product.materials', verbose_name='Материал'
                    ),
                ),
            ],
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fav_product',
                        to='product.product',
                        verbose_name='Товар',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fav_user',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={'verbose_name': 'Избранный товар', 'verbose_name_plural': 'Избранные товары'},
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='product_user_unique'),
        ),
    ]
