# Generated by Django 4.2.2 on 2023-06-18 12:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка на категорию')),
            ],
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название цвета')),
            ],
            options={'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название материала')),
            ],
            options={'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.PositiveIntegerField(unique=True, verbose_name='Артикул')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Название')),
                (
                    'width',
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(15000)], verbose_name='Ширина, см'
                    ),
                ),
                (
                    'height',
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(15000)], verbose_name='Высота, см'
                    ),
                ),
                (
                    'length',
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(15000)], verbose_name='Длина, см'
                    ),
                ),
                (
                    'weight',
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(500)], verbose_name='Вес, кг'
                    ),
                ),
                ('country', models.CharField(max_length=40, verbose_name='Страна-производитель')),
                ('brand', models.CharField(max_length=100, null=True, verbose_name='Бренд')),
                (
                    'warranty',
                    models.PositiveSmallIntegerField(
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(100)],
                        verbose_name='Гарантия , лет',
                    ),
                ),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.CharField(verbose_name='Описание')),
                (
                    'category',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to='product.category',
                        verbose_name='Категория',
                    ),
                ),
                (
                    'color',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to='product.color',
                        verbose_name='Цвет',
                    ),
                ),
                ('material', models.ManyToManyField(related_name='products', to='product.material')),
            ],
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'product',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fav_product',
                        to='product.product',
                        verbose_name='Товар',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='fav_user',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={'verbose_name': 'Избранный товар', 'verbose_name_plural': 'Избранные товары'},
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('product', 'user'), name='product_user_unique'),
        ),
    ]
