# Generated by Django 4.2.2 on 2023-06-21 06:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('product', '0003_alter_product_description')]

    operations = [migrations.RemoveField(model_name='product', name='discount')]
