# Generated by Django 4.2.2 on 2023-06-21 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('product', '0006_alter_discount_discount_created_at_and_more')]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='furniture_details',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='products',
                to='product.furnituredetails',
                verbose_name='Особенности конструкции',
            ),
        )
    ]
