# Generated by Django 4.2.2 on 2023-07-03 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0007_alter_product_furniture_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('id',), 'verbose_name': 'Коллекция', 'verbose_name_plural': 'Коллекции'},
        ),
        migrations.AlterModelOptions(
            name='color', options={'ordering': ('name',), 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'}
        ),
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('discount_created_at',), 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='furnituredetails',
            options={
                'ordering': ('purpose',),
                'verbose_name': 'Особенности конструкции',
                'verbose_name_plural': 'Особенности конструкций',
            },
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('name',), 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AlterModelOptions(
            name='product', options={'ordering': ('name',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'}
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cartitems',
                to='product.cartmodel',
                verbose_name='Корзина',
            ),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления в корзину'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cartitems',
                to='product.product',
                verbose_name='Товар',
            ),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления в корзине'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='cartmodel',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name='cartmodels', to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
