# Generated by Django 4.2.1 on 2023-06-10 08:37

import apps.users.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='user', name='first_name', field=models.CharField(blank=True, max_length=30, verbose_name='Имя')
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(
                choices=[('M', 'мужской'), ('W', 'женский')],
                default=('M', 'мужской'),
                max_length=30,
                verbose_name='Пол',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                max_length=30, unique=True, validators=[apps.users.validators.validate_phone], verbose_name='Телефон'
            ),
        ),
    ]
