# Generated by Django 4.2.2 on 2023-07-11 15:18

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0001_initial')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(
                blank=True,
                max_length=30,
                null=True,
                validators=[common.validators.validate_phone],
                verbose_name='Телефон',
            ),
        )
    ]
