# Generated by Django 4.2.1 on 2023-06-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0001_initial')]

    operations = [
        migrations.RemoveField(model_name='user', name='name'),
        migrations.AlterField(
            model_name='user', name='first_name', field=models.CharField(blank=True, max_length=50, verbose_name='Имя')
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user', name='phone', field=models.CharField(max_length=50, unique=True, verbose_name='Телефон')
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, verbose_name='Имя пользователя'),
        ),
    ]
