# Generated by Django 4.2.1 on 2023-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0003_alter_user_first_name_alter_user_last_name')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия'),
        ),
    ]
