# Generated by Django 4.2.1 on 2023-06-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('users', '0004_alter_user_first_name_alter_user_last_name')]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(
                choices=[('M', 'мужской'), ('W', 'женский')], default='M', max_length=30, verbose_name='Пол'
            ),
        )
    ]
